### ISSUE TITLE
Prescription bổ sung chức năng chọn mã máy khi thực hiện PT, TT

### ISSUE THREAD

**Issue by ongtrieuhau-dh** [dh-hos/THEO-DOI-THUC-HIEN-4750#34]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **ÔNG TRIỆU HẬU**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả khách hàng**
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả khách hàng**
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả khách hàng**

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

- Thực hiện xong cập nhật sản phẩm lên công việc: Theo Issue này
- Thực hiện xong cập nhật sản phẩm lên công việc: [Yêu cầu - Hỗ trợ test XML của quyết định 130](https://github.com/dh-hos/To_Ho_Tro/issues/20)
- Thực hiện xong cập nhật sản phẩm lên công việc: [Yêu cầu - Hỗ trợ test XML của quyết định 130](https://github.com/dh-hos/To_Trien_Khai/issues/57)
- Tài liệu chi tiết mô tả [Mô tả XML130 - Bổ sung QĐ 4750.md](https://github.com/dh-hos/Mo-ta-he-thong/blob/main/XML130/QD4570/M%C3%B4%20t%E1%BA%A3%20XML130%20-%20B%E1%BB%95%20sung%20Q%C4%90%204750.md)
- Chi tiết yêu cầu như sau:
![image](https://github.com/dh-hos/THEO-DOI-THUC-HIEN-4750/assets/155862740/65fcfccf-e2a8-4c19-b332-7d3d1a2b7b8b)

**Comment by ongtrieuhau-dh** [comment]
Lên hạn cái @lequocthong29

**Comment by lequocthong29** [comment]
Thực hiện - Prescription bổ sung chức năng chọn mã máy khi thực hiện PT, TT 
Hạn: 02/07/2024

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Prescription.exe v.3.24.0702.0 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32407020-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32407020-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32407020-NasDHSolutions.json)

## Nội dung thay đổi

- ✨: Bổ sung chức năng chọn mã máy khi thực hiện PT, TT

- ☑: https://github.com/dh-hos/THEO-DOI-THUC-HIEN-4750/issues/34

![](https://i.imgur.com/t4OK6OB.png)

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40lequocthong29-informational?logo=github)](https://github.com/lequocthong29) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Prescription.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by chauthanhtra** [comment]
Đã hỗ trợ nhập mã máy

![ảnh](https://github.com/user-attachments/assets/1d914c78-1ef9-414c-b19c-9c33ac8db4f2)
