### ISSUE TITLE
Treatment bổ sung mamay khi thực hiện ghi  nhận phiếu PT,TT

### ISSUE THREAD

**Issue by ongtrieuhau-dh** [dh-hos/THEO-DOI-THUC-HIEN-4750#35]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **ÔNG TRIỆU HẬU**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả khách hàng**
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả khách hàng**
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả khách hàng**

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

- Thực hiện xong cập nhật sản phẩm lên công việc: Theo Issue này
- Thực hiện xong cập nhật sản phẩm lên công việc: [Yêu cầu - Hỗ trợ test XML của quyết định 130](https://github.com/dh-hos/To_Ho_Tro/issues/20)
- Thực hiện xong cập nhật sản phẩm lên công việc: [Yêu cầu - Hỗ trợ test XML của quyết định 130](https://github.com/dh-hos/To_Trien_Khai/issues/57)
- Tài liệu chi tiết mô tả [Mô tả XML130 - Bổ sung QĐ 4750.md](https://github.com/dh-hos/Mo-ta-he-thong/blob/main/XML130/QD4570/M%C3%B4%20t%E1%BA%A3%20XML130%20-%20B%E1%BB%95%20sung%20Q%C4%90%204750.md)
- Lưu ý: lên hạn thực hiện khi tiếp nhận
- Chi tiết yêu cầu như sau:
![image](https://github.com/dh-hos/THEO-DOI-THUC-HIEN-4750/assets/155862740/ae11ae49-7bbe-4276-acc2-b572ce27d150)

**Comment by vuongdh** [comment]
Hạn: 05/7/2024

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Treatment.exe v.4.24.0705.0 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FTreatmentexe%2F42407050-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FTreatmentexe%2F42407050-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FTreatmentexe%2F42407050-NasDHSolutions.json)

## Nội dung thay đổi

- ✨: Treatment bổ sung mamay khi thực hiện ghi nhận phiếu PT,TT #35

- Bổ sung chức năng: ghi nhận mã máy vào phẫu thuật/thủ thuật

- phauthuat.mamay = dmmamay.mamay

![image](https://github.com/dh-hos/THEO-DOI-THUC-HIEN-4750/assets/32563776/19ef8506-4e51-4560-af50-bd4494843ac3)

Hiện thị danh mục mã máy kho cận lâm sàng

![image](https://github.com/dh-hos/THEO-DOI-THUC-HIEN-4750/assets/32563776/5d10bf03-078a-40c3-b32a-4cf7e281ea30)

![image](https://github.com/dh-hos/THEO-DOI-THUC-HIEN-4750/assets/32563776/9452e9a0-4175-4db7-8071-5a18acff3752)

- Bổ sung chức năng tóm tắt kết quả CLS có giá trị chẩn đoán vào form xuất viện (cột này là bắt buột nhập, hỗ trợ xuất xml8 )

![image](https://github.com/dh-hos/THEO-DOI-THUC-HIEN-4750/assets/32563776/25861284-4410-48a5-a2bc-96023ab8f635)

- ☑: https://github.com/dh-hos/THEO-DOI-THUC-HIEN-4750/issues/35

- ☑: https://github.com/dh-hos/To_Ho_Tro/issues/20

- ☑: https://github.com/dh-hos/To_Trien_Khai/issues/57

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40vuongdh-informational?logo=github)](https://github.com/vuongdh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Treatment.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Treatment.exe v.4.24.0705.1 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FTreatmentexe%2F42407051-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FTreatmentexe%2F42407051-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FTreatmentexe%2F42407051-NasDHSolutions.json)

## Nội dung thay đổi

- ✨: Yêu cầu - Khi lập phiếu PT, TT tại Prescription và Treatment bắt buộc phải nhập Ekip mới cho lưu. #432

- Fix lỗi không xóa được ekip

- ✨: Treatment bổ sung mamay khi thực hiện ghi nhận phiếu PT,TT #35

- Bổ sung chức năng: ghi nhận mã máy vào phẫu thuật/thủ thuật

- phauthuat.mamay = dmmamay.mamay

![image](https://github.com/dh-hos/THEO-DOI-THUC-HIEN-4750/assets/32563776/19ef8506-4e51-4560-af50-bd4494843ac3)

Hiện thị danh mục mã máy kho cận lâm sàng

![image](https://github.com/dh-hos/THEO-DOI-THUC-HIEN-4750/assets/32563776/5d10bf03-078a-40c3-b32a-4cf7e281ea30)

![image](https://github.com/dh-hos/THEO-DOI-THUC-HIEN-4750/assets/32563776/9452e9a0-4175-4db7-8071-5a18acff3752)

- Bổ sung chức năng tóm tắt kết quả CLS có giá trị chẩn đoán vào form xuất viện (cột này là bắt buột nhập, hỗ trợ xuất xml8 )

![image](https://github.com/dh-hos/THEO-DOI-THUC-HIEN-4750/assets/32563776/25861284-4410-48a5-a2bc-96023ab8f635)

- ☑: https://github.com/dh-hos/To_Lap_Trinh/issues/432

- ☑: https://github.com/dh-hos/THEO-DOI-THUC-HIEN-4750/issues/35

- ☑: https://github.com/dh-hos/To_Ho_Tro/issues/20

- ☑: https://github.com/dh-hos/To_Trien_Khai/issues/57

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40vuongdh-informational?logo=github)](https://github.com/vuongdh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Treatment.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by chauthanhtra** [comment]
Đã hỗ trợ nhập mã máy phiếu PT-TT

![ảnh](https://github.com/user-attachments/assets/d65f4c08-56d8-4866-9b36-636139ff6340)
