### ISSUE TITLE
Yêu cầu chỉnh số ngày uống (liều dùng) đúng theo từng mặt hàng trong toa

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/THEO-DOI-THUC-HIEN-4750#43]
Toa thuốc 10 ngày uống trong đó
- có thuốc uống trong 10 ngày.
- có thuốc uống trong 3 ngày.
Hiện tại liều dùng đang lấy số ngày uống theo số ngày của toa
-> đề xuất lấy đúng theo số ngày uống của từng mặt hàng
![ảnh](https://github.com/dh-hos/THEO-DOI-THUC-HIEN-4750/assets/96155021/fb3b6dbe-33ed-4d3f-ab1d-8ed55e98a015)
![ảnh](https://github.com/dh-hos/THEO-DOI-THUC-HIEN-4750/assets/96155021/96e1dc9c-a744-4f1d-9a75-55874c44f88c)

**Comment by ongtrieuhau-dh** [comment]
## HD.05 [^HD05]
-  ✔️ **Đã tiếp nhận** 
- ⌛ Thời gian hoàn thành dự kiến: **2024-07-09**


[^HD05]: Thời gian phải tiếp nhận ( Bình thường: 120 phút. Gấp: 60 phút) [Đối với các BL “Gấp” thời gian xử lý 4h, trường hợp không kịp bắc buộc phải đề ra các khắc phục tạm thời (Sql, lùi bản cũ…); Mức độ ưu tiên các lỗi “Gấp”: GĐ, tổ trưởng CO, tổ trưởng HT, tổ trưởng TK, nhân viên HT, nhân viên TK.]

**Comment by ongtrieuhau-dh** [comment]
## HD.09 [^HD09]
-  ✔️ **Phê duyệt YC theo HD.08** 
-  👉 **Assign**: @lequocthong29 
-  👉 **Thực hiện các yêu cầu theo luồng công việc này**
-  📣 **Lưu ý khi tiếp nhận**: 

1. _Ghi nhận thời gian hoàn thành dự kiến, theo định dạng yyyy-MM-dd, và thời gian hoàn thành không được lớn hơn thời gian dự kiến ở HD.05_ 
2. _Trường hợp không tiếp nhận hoặc thời gian không đúng với thời gian dự kiến ở HD.05 phải nêu rõ lý do._
3. _Theo dõi vi phạm HD.04 của luồng công việc này theo_ **HD.04** [^HD04]
4. _Cập  nhật sản phẩm để giải quyết luồng công việc này, diễn giải đầy đủ chức năng mới, chỉnh sửa lỗi theo mẫu READMECODING.md khi push code, có kèm hình ảnh hoặc tài liệu xác định đã có các chức năng mới, chỉnh lỗi xong._


[^HD09]: Thời gian phải tiếp nhận ( Bình thường: 120 phút. Gấp: 60 phút), Trách nhiệm: theo dõi đến khi Close Issue
[^HD04]: Nghĩa vụ: ghi nhận đầy đủ thông tin

**Comment by lequocthong29** [comment]
## HD.05
-  ✔️ **Đã tiếp nhận** 
-  👉 **Thực hiện**: Thêm Textbox để nhập ngày uống đối với từng mặt hàng và lấy liều dùng theo số ngày uống của từng mặt hàng .
-  📆 **Thời gian hoàn thành :** 2024-07-09.

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Prescription.exe v.3.24.0708.0 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32407080-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32407080-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32407080-NasDHSolutions.json)

## Nội dung thay đổi

- ✨: Liều dùng - lấy số ngày uống theo từng mặt hàng, dựa vào số lượng của từng mặt hàng và chỉ định sáng, trưa, chiều, tối

- ☑: https://github.com/dh-hos/THEO-DOI-THUC-HIEN-4750/issues/43

![](https://i.imgur.com/cWUB6d5.png)

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40lequocthong29-informational?logo=github)](https://github.com/lequocthong29) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Prescription.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by le-an-87** [comment]
ra toa báo lỗi này @lequocthong29 ơi
![ảnh](https://github.com/dh-hos/THEO-DOI-THUC-HIEN-4750/assets/96155021/c6759a9e-f490-4b4e-8b57-d3dd3c43cb80)

**Comment by le-an-87** [comment]
Đã cập nhật theo yêu cầu!
![ảnh](https://github.com/dh-hos/THEO-DOI-THUC-HIEN-4750/assets/96155021/155ad66f-e62b-4f69-adc3-9cb13c067e5b)
