### ISSUE TITLE
DANH MỤC ĐỊA PHƯƠNG 4750 TÊN VIẾT TẮT BỊ SAI

### ISSUE THREAD

**Issue by minhduc2it** [dh-hos/THEO-DOI-THUC-HIEN-4750#54]

**Comment by ongtrieuhau-dh** [comment]
Sai sao, cụ thể hơn đi @minhduc2it

**Comment by minhduc2it** [comment]
Tên huyện: Quận 10  -  Tên viết tắt: 1  (lấy thiếu số 0) 
Tên xã: Phường 10 - Tên viết tắt: 1  (lấy thiếu số 0)
Ps: Quận, phường có 2 chữ số từ 10 trở lên đang lấy sai

![image](https://github.com/dh-hos/THEO-DOI-THUC-HIEN-4750/assets/98437757/78ff53c6-1750-4337-9d75-ddae997a7145)

Yêu cầu: cách lấy tên viết tắt như DM địa phương cũ (để người dùng dễ nhập vì đã quen cách gõ tìm tên viết tắt cũ)
VD: Phường 10, Quận 10, Hồ Chí Minh -  Viết Tắt: HCMQ10P10
![image](https://github.com/dh-hos/THEO-DOI-THUC-HIEN-4750/assets/98437757/ea41b34a-1243-4666-8bde-95771970a911)

Dữ liệu: bi_bvclm_072024

**Comment by ongtrieuhau-dh** [comment]
## HD.05 [^HD05]
-  ✔️ **Đã tiếp nhận** 
- ⌛ Thời gian hoàn thành dự kiến: **2024-07-12**


[^HD05]: Thời gian phải tiếp nhận ( Bình thường: 120 phút. Gấp: 60 phút) [Đối với các BL “Gấp” thời gian xử lý 4h, trường hợp không kịp bắc buộc phải đề ra các khắc phục tạm thời (Sql, lùi bản cũ…); Mức độ ưu tiên các lỗi “Gấp”: GĐ, tổ trưởng CO, tổ trưởng HT, tổ trưởng TK, nhân viên HT, nhân viên TK.]

**Comment by ongtrieuhau-dh** [comment]
## HD.09 [^HD09]
-  ✔️ **Phê duyệt YC theo HD.08** 
-  👉 **Assign**: @lequocthong29 
-  👉 **Thực hiện các yêu cầu theo luồng công việc này**
-  📣 **Lưu ý khi tiếp nhận**: 

1. _Ghi nhận thời gian hoàn thành dự kiến, theo định dạng yyyy-MM-dd, và thời gian hoàn thành không được lớn hơn thời gian dự kiến ở HD.05_ 
2. _Trường hợp không tiếp nhận hoặc thời gian không đúng với thời gian dự kiến ở HD.05 phải nêu rõ lý do._
3. _Theo dõi vi phạm HD.04 của luồng công việc này theo_ **HD.04** [^HD04]
4. _Cập  nhật sản phẩm để giải quyết luồng công việc này, diễn giải đầy đủ chức năng mới, chỉnh sửa lỗi theo mẫu READMECODING.md khi push code, có kèm hình ảnh hoặc tài liệu xác định đã có các chức năng mới, chỉnh lỗi xong._


[^HD09]: Thời gian phải tiếp nhận ( Bình thường: 120 phút. Gấp: 60 phút), Trách nhiệm: theo dõi đến khi Close Issue
[^HD04]: Nghĩa vụ: ghi nhận đầy đủ thông tin

**Comment by lequocthong29** [comment]
## HD.05
-  ✔️ **Đã tiếp nhận** 
-  👉 **Thực hiện**: Fix lỗi - DANH MỤC ĐỊA PHƯƠNG 4750 SAI TÊN VIẾT TẮT.
-  📆 **Thời gian hoàn thành :**  2024-07-12.

**Comment by minhduc2it** [comment]
Chỗ Thị xã: thì tên viết tắt lấy tên thôi bỏ Xã
VD: Thị xã Buôn Hồ >> BH
Hiện tại pm đang lấy XBH

![Image](https://github.com/dh-hos/THEO-DOI-THUC-HIEN-4750/assets/98437757/97679469-a037-4f8a-9a08-0100e29175fe)

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 HospitalAdmin.exe v.3.24.0710.1 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalAdminexe%2F32407101-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalAdminexe%2F32407101-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalAdminexe%2F32407101-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Fix lỗi - DANH MỤC ĐỊA PHƯƠNG 4750 TÊN VIẾT TẮT BỊ SAI

- ☑: https://github.com/dh-hos/THEO-DOI-THUC-HIEN-4750/issues/54

![](https://i.imgur.com/yzMsYaF.png)

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40lequocthong29-informational?logo=github)](https://github.com/lequocthong29) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/HospitalAdmin.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by lequocthong29** [comment]
@ongtrieuhau  e fix chung với bản cập nhật trên luôn rồi a

**Comment by ongtrieuhau** [comment]
Cái này phải mở form mới fix hay sao? Hướng dẫn cụ thể?

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 HospitalAdmin.exe v.3.24.0710.2 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalAdminexe%2F32407102-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalAdminexe%2F32407102-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalAdminexe%2F32407102-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Fix - DANH MỤC ĐỊA PHƯƠNG 4750 TÊN VIẾT TẮT BỊ SAI #54

- Trường hợp viettat lấy sai tenhuyen

- ☑: https://github.com/dh-hos/THEO-DOI-THUC-HIEN-4750/issues/54

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40lequocthong29-informational?logo=github)](https://github.com/lequocthong29) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/HospitalAdmin.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by lequocthong29** [comment]
@ongtrieuhau @minhduc2it Người dùng add lại DM địa phương để tự động cập nhật lại phần viết tắt hoặc cập nhật cấu trúc

**Comment by minhduc2it** [comment]
Đã kiểm tra hỗ trợ theo yêu cầu 

![Image](https://github.com/dh-hos/THEO-DOI-THUC-HIEN-4750/assets/98437757/5754e763-a4ac-4e70-9b1b-2abd1d265092)

![Image](https://github.com/dh-hos/THEO-DOI-THUC-HIEN-4750/assets/98437757/bd37fd13-8a40-4891-be15-103273610788)
