### ISSUE TITLE
LỖI - LOẠI CLS TEST TÂM LÝ CHƯA LẤY ĐƯỢC NGUOI_THUC_HIEN TRÊN XML3

### ISSUE THREAD

**Issue by minhduc2it** [dh-hos/THEO-DOI-THUC-HIEN-4750#62]

**Comment by minhduc2it** [comment]
Data: duc_tamthan
Loại CLS Test Tâm lý chưa lấy được NGUOI_THUC_HIEN TRÊN XML3 
![image](https://github.com/user-attachments/assets/53d9afb6-dde2-40a6-a05e-3c68048325e9)

1. Trên Pre khám bệnh: MABN: 2020003279 - MAKB: 2407001390 - NgayKCB: 09/7/2024
![image](https://github.com/user-attachments/assets/b8a3d81d-4785-4d6e-99ce-d8aff5a575e5)

![image](https://github.com/user-attachments/assets/af5364a6-8619-49ea-808a-b05c02b336a2)

2. Trên Pre BANT: MABN: 2020010257 - MAKB: 2407001643 - MABA: N2024002861 - NgayKCB: 10/7/2024
![image](https://github.com/user-attachments/assets/56570487-597d-4697-bb59-15e3c6c9740a)

![image](https://github.com/user-attachments/assets/ca3dac83-6ef5-4d99-9987-81e6a80f3427)

3. Trên Pre BANT: MABN: 2024002736 - MAKB: 2406001753 - MABA: 2024000555 - NgayKCB: 13/6/2024
![image](https://github.com/user-attachments/assets/05d171b8-b89e-44ec-8411-73fd31309506)

![image](https://github.com/user-attachments/assets/c02f91b6-dcfc-4334-b1a2-2b71d2b59f5a)

**Comment by ongtrieuhau-dh** [comment]
## HD.05 [^HD05]
-  ✔️ **Đã tiếp nhận** 
- ⌛ Thời gian hoàn thành dự kiến: **2024-07-17**


[^HD05]: Thời gian phải tiếp nhận ( Bình thường: 120 phút. Gấp: 60 phút) [Đối với các BL “Gấp” thời gian xử lý 4h, trường hợp không kịp bắc buộc phải đề ra các khắc phục tạm thời (Sql, lùi bản cũ…); Mức độ ưu tiên các lỗi “Gấp”: GĐ, tổ trưởng CO, tổ trưởng HT, tổ trưởng TK, nhân viên HT, nhân viên TK.]

**Comment by ongtrieuhau-dh** [comment]
## HD.09 [^HD09]
-  ✔️ **Phê duyệt YC theo HD.08** 
-  👉 **Assign**: @vinh-dh 
-  👉 **Thực hiện các yêu cầu theo luồng công việc này**
-  📣 **Lưu ý khi tiếp nhận**:  Bổ sung mô tả thêm trường hợp này, trong mô tả còn thiếu 
![image](https://github.com/user-attachments/assets/b5e638f2-dda5-44e1-91da-026a1e800028)


1. _Ghi nhận thời gian hoàn thành dự kiến, theo định dạng yyyy-MM-dd, và thời gian hoàn thành không được lớn hơn thời gian dự kiến ở HD.05_ 
2. _Trường hợp không tiếp nhận hoặc thời gian không đúng với thời gian dự kiến ở HD.05 phải nêu rõ lý do._
3. _Theo dõi vi phạm HD.04 của luồng công việc này theo_ **HD.04** [^HD04]
4. _Cập  nhật sản phẩm để giải quyết luồng công việc này, diễn giải đầy đủ chức năng mới, chỉnh sửa lỗi theo mẫu READMECODING.md khi push code, có kèm hình ảnh hoặc tài liệu xác định đã có các chức năng mới, chỉnh lỗi xong._


[^HD09]: Thời gian phải tiếp nhận ( Bình thường: 120 phút. Gấp: 60 phút), Trách nhiệm: theo dõi đến khi Close Issue
[^HD04]: Nghĩa vụ: ghi nhận đầy đủ thông tin

**Comment by vinh-dh** [comment]
## HD.05
- ✔️ Đã tiếp nhận.
- 👉 Để anh kiểm tra lỗi và bổ sung mô tả trường hợp này.
![image](https://github.com/user-attachments/assets/b5e638f2-dda5-44e1-91da-026a1e800028)
- ⌛ Thời gian hoàn thành dự kiến: 2024-07-17

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 HospitalAdmin.exe v.3.24.0712.0 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalAdminexe%2F32407120-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalAdminexe%2F32407120-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalAdminexe%2F32407120-NasDHSolutions.json)

## Nội dung thay đổi

- ✨: XML01.MA_BENH_KT theo tham số ma_benh_kt.soluong [Mô tả XML130 - Bổ sung QĐ 4750](https://github.com/dh-hos/Mo-ta-he-thong/blob/main/XML130/QD4570/M%C3%B4%20t%E1%BA%A3%20XML130%20-%20B%E1%BB%95%20sung%20Q%C4%90%204750.md)

- ✨: XML01 và Checkin: MA_DOITUONG_KCB [Table xml130.bang01](https://github.com/dh-hos/Mo-ta-he-thong/blob/main/XML130/QD4570/Table%20xml130.bang01%20-%20%5BPh%E1%BB%A5%20l%E1%BB%A5c%20-%20M%C3%B4%20t%E1%BA%A3%20XML130%20-%20B%E1%BB%95%20sung%20Q%C4%90%204750%5D.md#user-content-fnref-2024-07-12-02-1ec9d201cbe3c6fd4b2a050757091faf)

- 🐛: XML01.NGUOI_THUC_HIEN, NGAY_TH_YL đối với Loại CLS (TL: Test tâm lý)

![](https://i.imgur.com/CfraF7I.png)

- ☑: https://github.com/dh-hos/To_Ho_Tro/issues/20

- ☑: https://github.com/dh-hos/To_Trien_Khai/issues/57

- ☑: https://github.com/dh-hos/To_Lap_Trinh/issues/479

- ☑: https://github.com/dh-hos/THEO-DOI-THUC-HIEN-4750/issues/62

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau--dh-informational?logo=github)](https://github.com/ongtrieuhau-dh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/HospitalAdmin.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by vinh-dh** [comment]
Cập nhật mô tả [xml130.bang3](https://github.com/dh-hos/Mo-ta-he-thong/blob/main/XML130/QD4570/Table%20xml130.bang03%20-%20%5BPh%E1%BB%A5%20l%E1%BB%A5c%20-%20M%C3%B4%20t%E1%BA%A3%20XML130%20-%20B%E1%BB%95%20sung%20Q%C4%90%204750%5D.md): Chỉ tiêu chi tiết dịch vụ kỹ thuật và vật tư y tế.
- Bổ sung điều kiện ràng buộc cho cột `nguoi_thuc_hien` đối với `ma_nhom = 3` và `maloai = 'TL'`.

**Comment by vinh-dh** [comment]
Cập nhật mô tả [xml130.bang3](https://github.com/dh-hos/Mo-ta-he-thong/blob/main/XML130/QD4570/Table%20xml130.bang03%20-%20%5BPh%E1%BB%A5%20l%E1%BB%A5c%20-%20M%C3%B4%20t%E1%BA%A3%20XML130%20-%20B%E1%BB%95%20sung%20Q%C4%90%204750%5D.md): Chỉ tiêu chi tiết dịch vụ kỹ thuật và vật tư y tế.
- Bổ sung điều kiện ràng buộc cho cột `ngay_th_yl` đối với `ma_nhom = 3` và `maloai = 'TL'`.

**Comment by minhduc2it** [comment]
Đã kiểm tra XML3 Loại CLS: TL đã lấy được Nguoi_thuc_hien và gửi thử cổng thành công
![image](https://github.com/user-attachments/assets/b313a78f-423f-4ab1-ba78-a8fa626f5c18)
