### ISSUE TITLE
📘 Yêu cầu - Prescription - Ràng buộc không bỏ trống phương tiện vận chuyển khi lập phiếu chuyển tuyến  ⏳Dự kiến :  2024-07-24

### ISSUE THREAD

**Issue by ongtrieuhau-dh** [dh-hos/THEO-DOI-THUC-HIEN-4750#77]
## HD.09 [^HD09]
-  ✔️ **Phê duyệt YC theo HD.08** 
-  👉 **Assign**: @lequocthong29 
-  👉 **Thực hiện các yêu cầu theo luồng công việc này**
-  📣 **Lưu ý khi tiếp nhận**: 

1. _Ghi nhận thời gian hoàn thành dự kiến, theo định dạng yyyy-MM-dd, và thời gian hoàn thành không được lớn hơn thời gian dự kiến ở HD.05_ 
2. _Trường hợp không tiếp nhận hoặc thời gian không đúng với thời gian dự kiến ở HD.05 phải nêu rõ lý do._
3. _Theo dõi vi phạm HD.04 của luồng công việc này theo_ **HD.04** [^HD04]
4. _Cập  nhật sản phẩm để giải quyết luồng công việc này, diễn giải đầy đủ chức năng mới, chỉnh sửa lỗi theo mẫu READMECODING.md khi push code, có kèm hình ảnh hoặc tài liệu xác định đã có các chức năng mới, chỉnh lỗi xong._

[^HD09]: Thời gian phải tiếp nhận ( Bình thường: 120 phút. Gấp: 60 phút), Trách nhiệm: theo dõi đến khi Close Issue
[^HD04]: Nghĩa vụ: ghi nhận đầy đủ thông tin

**Comment by lequocthong29** [comment]
## HD.05
-  ✔️ **Đã tiếp nhận** 
-  👉 **Thực hiện**: Ràng buộc không bỏ trống phương tiện vận chuyển khi lập phiếu chuyển tuyến.
-  📆 **Thời gian hoàn thành :**  2024-07-24.
