### ISSUE TITLE
📘 Yêu cầu - Treatment - Ràng buộc không bỏ trống phương tiện vận chuyển khi lập phiếu chuyển tuyến  ⏳Dự kiến :  2024-07-24

### ISSUE THREAD

**Issue by ongtrieuhau-dh** [dh-hos/THEO-DOI-THUC-HIEN-4750#78]
## HD.09 [^HD09]
-  ✔️ **Phê duyệt YC theo HD.08** 
-  👉 **Assign**: @vuongdh 
-  👉 **Thực hiện các yêu cầu theo luồng công việc này**
-  📣 **Lưu ý khi tiếp nhận**: 

1. _Ghi nhận thời gian hoàn thành dự kiến, theo định dạng yyyy-MM-dd, và thời gian hoàn thành không được lớn hơn thời gian dự kiến ở HD.05_ 
2. _Trường hợp không tiếp nhận hoặc thời gian không đúng với thời gian dự kiến ở HD.05 phải nêu rõ lý do._
3. _Theo dõi vi phạm HD.04 của luồng công việc này theo_ **HD.04** [^HD04]
4. _Cập  nhật sản phẩm để giải quyết luồng công việc này, diễn giải đầy đủ chức năng mới, chỉnh sửa lỗi theo mẫu READMECODING.md khi push code, có kèm hình ảnh hoặc tài liệu xác định đã có các chức năng mới, chỉnh lỗi xong._

[^HD09]: Thời gian phải tiếp nhận ( Bình thường: 120 phút. Gấp: 60 phút), Trách nhiệm: theo dõi đến khi Close Issue
[^HD04]: Nghĩa vụ: ghi nhận đầy đủ thông tin

**Comment by vuongdh** [comment]
✔️ Đã tiếp nhận
⌛ Thời gian hoàn thành dự kiến: 2024-07-24

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Treatment.exe v.4.24.0722.0 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FTreatmentexe%2F42407220-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FTreatmentexe%2F42407220-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FTreatmentexe%2F42407220-NasDHSolutions.json)

## Nội dung thay đổi

- ✨: Treatment - RÀNG BUỘC KHÔNG BỎ TRỐNG HƯỚNG ĐIỀU TRỊ CHO GIẤY CHUYỂN TUYẾN #506

- ✨: Yêu cầu - RÀNG BUỘC KHÔNG BỎ TRỐNG HƯỚNG ĐIỀU TRỊ CHO GIẤY CHUYỂN TUYẾN #504

- Cập nhật không để trống hướng điều trị trên giấy chuyển tuyến

- ☑: https://github.com/dh-hos/To_Lap_Trinh/issues/506

- ☑: https://github.com/dh-hos/To_Lap_Trinh/issues/504

- ✨: Yêu cầu - Treatment - Ràng buộc không bỏ trống phương tiện vận chuyển khi lập phiếu chuyển tuyến

- ✨: Yêu cầu - Ràng buộc không bỏ trống phương tiện vận chuyển khi lập phiếu chuyển tuyến #510

- Cập nhật không để trống phương tiện vận chuyển trên giấy chuyển tuyến

- ☑: https://github.com/dh-hos/THEO-DOI-THUC-HIEN-4750/issues/78

- ☑: https://github.com/dh-hos/To_Lap_Trinh/issues/510

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40vuongdh-informational?logo=github)](https://github.com/vuongdh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Treatment.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>
